
FROM python:3.7

WORKDIR /code

COPY ./docker_requirements.txt .
RUN pip install -r docker_requirements.txt

COPY ./ift6758 /code/ift6758
RUN pip install -e /code/ift6758

# Copy the rest of the application code
COPY ./ift6758/milestone_3 .

# Expose the port your Streamlit app runs on
EXPOSE 8501

# Command to run the Streamlit application
CMD ["streamlit", "run", "streamlit/streamlit_app.py", "--server.address=0.0.0.0"]

